name: Unity CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Unity
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 2021.3.29f1

    - name: Build project
      uses: game-ci/unity-builder@v2
      with:
        targetPlatform: StandaloneWindows64

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Unity
      uses: game-ci/unity-test-runner@v2
      with:
        unityVersion: 2021.3.29f1

    - name: Run tests
      uses: game-ci/unity-test-runner@v2
      with:
        testMode: playmode
